# Generated by Django 3.1.3 on 2021-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='display_name',
            field=models.CharField(help_text='Display name should stary with a capital letter', max_length=30, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name'),
        ),
    ]
