# Generated by Django 3.1.3 on 2021-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20210529_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='display_name',
            field=models.CharField(default='majdan', max_length=30, verbose_name='Country name'),
            preserve_default=False,
        ),
    ]
