# Generated by Django 3.1.3 on 2021-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20210529_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='display_name',
            field=models.CharField(help_text='Display name should stary with a capital letter', max_length=30, verbose_name='Display name'),
        ),
    ]
