# Generated by Django 3.1.3 on 2021-05-31 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival time')),
                ('tickets_type', models.CharField(choices=[('first', 'First class ticket'), ('second', 'Second class ticket')], max_length=30)),
                ('first_class_ticket_quantity', models.PositiveIntegerField(default=0, verbose_name='First class ticket quantity')),
                ('first_class_ticket_price', models.PositiveSmallIntegerField(default=0, verbose_name='First class ticket price')),
                ('is_active', models.BooleanField(default=False, verbose_name='Flight is active')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_location', to='cities.city', verbose_name='From location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_location', to='cities.city', verbose_name='To location')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
