# Generated by Django 3.2.3 on 2021-05-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_delete_ticket'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
