# Generated by Django 3.1.3 on 2021-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_first_class_ticket_quantity',
            field=models.PositiveIntegerField(blank=True, default=2, verbose_name='First class ticket quantity'),
            preserve_default=False,
        ),
    ]
