# Generated by Django 3.1.3 on 2021-05-31 22:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_available_first_class_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='first_class_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='First class ticket price'),
        ),
    ]
