# Generated by Django 3.1.3 on 2021-06-01 08:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20210601_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='tickets_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('first', 'First class ticket'), ('second', 'Second class ticket')], max_length=30),
        ),
    ]
