# Generated by Django 3.1.3 on 2021-06-03 15:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20210602_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_second_class_ticket_quantity',
            field=models.PositiveIntegerField(blank=True, default=2, verbose_name='Second class ticket quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='second_class_ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Second class ticket price'),
        ),
        migrations.AddField(
            model_name='flight',
            name='second_class_ticket_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Second class ticket quantity'),
        ),
    ]
