# Generated by Django 3.1.3 on 2021-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20210603_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_first_class_ticket_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='First class ticket quantity'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_second_class_ticket_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Second class ticket quantity'),
        ),
    ]
