# Generated by Django 3.1.3 on 2021-05-31 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0002_flight_available_first_class_ticket_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Discount name')),
                ('discount_percentage', models.IntegerField(verbose_name='Discount percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('type', models.CharField(choices=[('first', 'First class ticket'), ('second', 'Second class ticket')], max_length=30, verbose_name='Ticket type')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Ticket price')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='tickets.discount')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='flights.flight', verbose_name='Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
