# Generated by Django 3.2.3 on 2021-05-27 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0003_flight'),
        ('tickets', '0002_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('type', models.CharField(choices=[('first', 'First class ticket'), ('second', 'Second class ticket')], max_length=30, verbose_name='Ticket type')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Ticket price')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.flight', verbose_name='Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
