# Generated by Django 3.1.3 on 2021-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210601_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Additional service name')),
                ('service_price', models.IntegerField(verbose_name='Additional service price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='tickets', to='tickets.Service'),
        ),
    ]
