# Generated by Django 3.1.3 on 2021-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210601_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.Service'),
        ),
    ]
